#!/bin/bash

failed_items=""
function install_package() {
echo EXECUTING: brew install $1 $2
brew install $1 $2
[ $? -ne 0 ] && $failed_items="$failed_items $1" # package failed to install.
}
brew tap ==> Auto-updated Homebrew!
brew tap Updated 2 taps (caskroom/cask, homebrew/core).
brew tap No changes to formulae.
brew tap 
brew tap caskroom/cask
brew tap homebrew/core
brew tap homebrew/dupes
brew tap homebrew/science
install_package boost ''
install_package boost-python ''
install_package cmake ''
install_package coreutils ''
install_package cscope ''
install_package dcraw ''
install_package dos2unix ''
install_package eigen ''
install_package emacs ''
install_package espeak ''
install_package ffmpeg ''
install_package freetype ''
install_package gdbm ''
install_package gettext ''
install_package ghostscript ''
install_package git ''
install_package glib ''
install_package gnu-sed ''
install_package go ''
install_package graphviz ''
install_package grep ''
install_package ilmbase ''
install_package imagemagick ''
install_package jasper ''
install_package jpeg ''
install_package jq ''
install_package lame ''
install_package libevent ''
install_package libffi ''
install_package libpng ''
install_package libtiff ''
install_package libtool ''
install_package libyaml ''
install_package little-cms ''
install_package little-cms2 ''
install_package macvim ''
install_package mercurial ''
install_package mysql ''
install_package nmap ''
install_package numpy ''
install_package oniguruma ''
install_package opencv ''
install_package openexr ''
install_package openssl ''
install_package pcre ''
install_package perl ''
install_package pkg-config ''
install_package portaudio ''
install_package portmidi ''
install_package python ''
install_package python3 ''
install_package qcachegrind ''
install_package qt ''
install_package qt5 ''
install_package readline ''
install_package reattach-to-user-namespace ''
install_package ruby ''
install_package sdl ''
install_package sdl2 ''
install_package sdl_image ''
install_package sdl_mixer ''
install_package sdl_ttf ''
install_package sl ''
install_package sqlite ''
install_package swig ''
install_package the_silver_searcher ''
install_package tmux ''
install_package tree ''
install_package ufraw ''
install_package utf8proc ''
install_package vim ''
install_package webp ''
install_package wget ''
install_package x264 ''
install_package xvid ''
install_package xz ''
install_package zbar ''
[ ! -z $failed_items ] && echo The following items were failed to install: && echo $failed_items
